# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-US
  contentDir: content/en
  title: 鴻盛昌資源集團有限公司 HSC RESOURCES GROUP LIMITED
  params:
    description: 鴻盛昌資源集團有限公司 HSC RESOURCES GROUP LIMITED
    locale:
      date_format: 'Jan 2, 2006'
      time_format: '3:04 PM'
    footer:
      copyright:
        notice: '© {year} HSC RESOURCES GROUP LIMITED'
  menu:
    main:
      - name: Homepage
        url: en
        weight: 10
      - name: Introduction
        url: en/intro
        weight: 20
      # - name: News
      #   url: post
      #   weight: 30
      - name: Business
        url: en/business
        weight: 40
      - name: Plan
        url: en/plan
        weight: 50
      - name: Report
        url: en/report
        weight: 60
      - name: Contact
        url: en/contact
        weight: 70

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 鸿盛昌资源集团有限公司 HSC RESOURCES GROUP LIMITED
  params:
    description: 鸿盛昌资源集团有限公司 HSC RESOURCES GROUP LIMITED
    locale:
      date_format: '2006年 Jan 02日'
      time_format: '15:04'
    footer:
      copyright:
        notice: '© {year} 鸿盛昌资源集团有限公司 HSC RESOURCES GROUP LIMITED'
  menu:
    main:
      - name: 首页
        url: /
        weight: 10
      - name: 简介
        url: zh/intro
        weight: 20
      # - name: 公司新闻
      #   url: post
      #   weight: 30
      - name: 主要业务
        url: zh/business
        weight: 40
      - name: 未来规划
        url: zh/plan
        weight: 50
      - name: 公司年报
        url: zh/report
        weight: 60
      - name: 联络我们
        url: zh/contact
        weight: 70

zh-hant:
  languageCode: zh-Hant
  contentDir: content/zh-hant
  title: 鴻盛昌資源集團有限公司 HSC RESOURCES GROUP LIMITED
  params:
    description: 鴻盛昌資源集團有限公司 HSC RESOURCES GROUP LIMITED
    locale:
      date_format: '2006年 Jan 02日'
      time_format: '15:04'
    footer:
      copyright:
        notice: '© {year} 鴻盛昌資源集團有限公司 HSC RESOURCES GROUP LIMITED'
  menu:
    main:
      - name: 首頁
        url: /
        weight: 10
      - name: 簡介
        url: intro
        weight: 20
      # - name: 公司新聞
      #   url: post
      #   weight: 30
      - name: 主要業務
        url: business
        weight: 40
      - name: 未來規劃
        url: plan
        weight: 50
      - name: 公司年報
        url: report
        weight: 60
      - name: 聯絡我們
        url: contact
        weight: 70