name = "HSC RESOURCES GROUP LIMITED"
license = "MIT"
licenselink = "https://github.com/robhker/landing/blob/main/LICENSE.md"
description = "HSC RESOURCES GROUP LIMITED"
homepage = "https://hscgroup.hk"
demosite = "https://hscgroup.hk"

[author]
  name = "HSC RESOURCES GROUP LIMITED"
  homepage = "https://hscgroup.hk"
